### ISSUE TITLE
DXF file can not be opened

### ISSUE THREAD

**Issue by ghost** [mariolukas/FabScan-Case#8]
The DXF file of the case provided in the repo (FabScan_Pi_V20.dxf) can not be opened. Not even with Autodesk's own tools (Fusion 360, DWG TrueView). Error output of DWG TrueView:

Skipping duplicate definition of EBENE_1 in LAYER TableSkipping duplicate definition of 0 in LAYER Table
The following error was encountered while reading in SPLINE starting at line 12016:
Neither control points nor fit points supplied
Invalid or incomplete DXF input -- drawing discarded.

**Comment by bondjames12** [comment]
I'm building the fabscan this week. I used FreeCAD to open FabScan_Pi_V20.dxf it seemed to work fine with that tool. (https://github.com/FreeCAD/FreeCAD)

**Comment by dvanp** [comment]
Not working for me either. Tried Fusion 360, FreeCAD and a lot of online viewers. Also a few lasercutting services I wanted to get a quote cannot process the file.

**Comment by mariolukas** [comment]
I will try to provide new SVG files as soon as possible.
